{{- $name := include "workadventure.uploader.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ printf "%s.%s" $.Values.uploader.name $.Values.domain }}
spec:
  type: {{ .Values.uploader.service.type }}
  ports:
    - port: {{ .Values.uploader.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "workadventure.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: "{{ .Values.uploader.name }}"
